# Generated by Django 6.0.5 on 2026-08-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globetrotter', '0002_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='trips', to='globetrotter.user'),
        ),
    ]
