# Generated by Django 6.0.5 on 2026-08-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globetrotter', '0003_remove_trip_user_trip_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='end_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='duration_days',
            field=models.PositiveIntegerField(default=7),
            preserve_default=False,
        ),
    ]
